apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - https://github.com/superbet-group/betting.platform.infrastructure//components/kafka-topic/delete
patchesStrategicMerge:
  - ./topic.yaml