apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-topic
spec:
  partitions: 8
  replicas: 3
  config:
    cleanup.policy: compact,delete
    delete.retention.ms: 259200000
    min.compaction.lag.ms: 86400000
    retention.ms: 259200000